### ISSUE TITLE
Wrong comparison in the implementation of reactive()

### ISSUE THREAD

**Issue by gregaton** [Code-Pop/vue-3-reactivity#1]
I just went through your amazing tutorial and found a small bug in the implementation of the `reactive` function.
`Reflect.set()` returns a boolean indicating whether or not setting the property was successful.
In the next line that boolean is compared to `oldValue` to decide whether or not to invoke `trigger()` but I think it should be compared against `value` and just check if the boolean is true.
For comparison:
```javascript
      let result = Reflect.set(target, key, value, receiver)
      if (oldValue != result) { // <= here is the mistake
        trigger(target, key) // If this reactive property (target) has effects to rerun on SET, trigger them.
      }
```
should be something like
```javascript
      let result = Reflect.set(target, key, value, receiver)
      if (result && oldValue != value) { // maybe that check should happen before the Reflect.set?
        trigger(target, key) // If this reactive property (target) has effects to rerun on SET, trigger them.
      }
```

**Comment by MarvinXu** [comment]
I have the same doubt, must be wrong.

**Comment by LookRain** [comment]
+1

**Comment by Gregg** [comment]
Sorry about the delay on this one, but thank you for the heads up. I've fixed this in the course and in the code.
